name: Build and Commit PrevEve

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for committing to the repository

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Cache apt packages to speed up dependency installation
    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          make \
          qt6-base-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libpipewire-0.3-dev

    # Configure the project with CMake in a build directory
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$PWD/bin

    # Build the project with Make
    - name: Build
      run: |
        cd build
        make -j$(nproc)

    # Verify and copy the executable to the repository root
    - name: Copy executable to root
      run: |
        ls -l build/bin/PrevEve || { echo "Error: PrevEve not found"; exit 1; }
        chmod +x build/bin/PrevEve
        cp build/bin/PrevEve ../PrevEve
        ls -l ../PrevEve

    # Upload executable as an artifact (optional, for debugging)
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrevEve-executable
        path: PrevEve
        retention-days: 5

    # Commit and push the executable to the repository
    - name: Commit PrevEve to repository
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add PrevEve
        git commit -m "Add compiled PrevEve executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
