name: Build and Commit PrevEve

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for committing to the repository

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Cache apt packages to speed up dependency installation
    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          make \
          qt6-base-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libpipewire-0.3-dev
        # Clean up lock files to avoid tar issues
        sudo rm -f /var/cache/apt/archives/lock
        sudo rm -f /var/cache/apt/archives/partial/*
      continue-on-error: true # Allow build to proceed if apt fails

    # Configure the project with CMake in a build directory
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$PWD/bin

    # Build the project with Make
    - name: Build
      run: |
        cd build
        make -j$(nproc)

    # Verify and copy the executable to the repository root
    - name: Copy executable to root
      run: |
        ls -l build/bin/eve-w-preview || { echo "Error: eve-w-preview not found"; exit 1; }
        chmod +x build/bin/eve-w-preview
        cp build/bin/eve-w-preview ../eve-w-preview
        ls -l ../eve-w-preview

    # Upload executable as an artifact (optional, for debugging)
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrevEve-executable
        path: PrevEve
        retention-days: 5

    # Commit and push the executable to the repository
    - name: Commit PrevEve to repository
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add PrevEve
        git commit -m "Add compiled PrevEve executable" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
